require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SituationGeosmapsController do

  # This should return the minimal set of attributes required to create a valid
  # SituationGeosmap. As you add validations to SituationGeosmap, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SituationGeosmapsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all situation_geosmaps as @situation_geosmaps" do
      situation_geosmap = SituationGeosmap.create! valid_attributes
      get :index, {}, valid_session
      assigns(:situation_geosmaps).should eq([situation_geosmap])
    end
  end

  describe "GET show" do
    it "assigns the requested situation_geosmap as @situation_geosmap" do
      situation_geosmap = SituationGeosmap.create! valid_attributes
      get :show, {:id => situation_geosmap.to_param}, valid_session
      assigns(:situation_geosmap).should eq(situation_geosmap)
    end
  end

  describe "GET new" do
    it "assigns a new situation_geosmap as @situation_geosmap" do
      get :new, {}, valid_session
      assigns(:situation_geosmap).should be_a_new(SituationGeosmap)
    end
  end

  describe "GET edit" do
    it "assigns the requested situation_geosmap as @situation_geosmap" do
      situation_geosmap = SituationGeosmap.create! valid_attributes
      get :edit, {:id => situation_geosmap.to_param}, valid_session
      assigns(:situation_geosmap).should eq(situation_geosmap)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SituationGeosmap" do
        expect {
          post :create, {:situation_geosmap => valid_attributes}, valid_session
        }.to change(SituationGeosmap, :count).by(1)
      end

      it "assigns a newly created situation_geosmap as @situation_geosmap" do
        post :create, {:situation_geosmap => valid_attributes}, valid_session
        assigns(:situation_geosmap).should be_a(SituationGeosmap)
        assigns(:situation_geosmap).should be_persisted
      end

      it "redirects to the created situation_geosmap" do
        post :create, {:situation_geosmap => valid_attributes}, valid_session
        response.should redirect_to(SituationGeosmap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved situation_geosmap as @situation_geosmap" do
        # Trigger the behavior that occurs when invalid params are submitted
        SituationGeosmap.any_instance.stub(:save).and_return(false)
        post :create, {:situation_geosmap => {  }}, valid_session
        assigns(:situation_geosmap).should be_a_new(SituationGeosmap)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SituationGeosmap.any_instance.stub(:save).and_return(false)
        post :create, {:situation_geosmap => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested situation_geosmap" do
        situation_geosmap = SituationGeosmap.create! valid_attributes
        # Assuming there are no other situation_geosmaps in the database, this
        # specifies that the SituationGeosmap created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SituationGeosmap.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => situation_geosmap.to_param, :situation_geosmap => { "these" => "params" }}, valid_session
      end

      it "assigns the requested situation_geosmap as @situation_geosmap" do
        situation_geosmap = SituationGeosmap.create! valid_attributes
        put :update, {:id => situation_geosmap.to_param, :situation_geosmap => valid_attributes}, valid_session
        assigns(:situation_geosmap).should eq(situation_geosmap)
      end

      it "redirects to the situation_geosmap" do
        situation_geosmap = SituationGeosmap.create! valid_attributes
        put :update, {:id => situation_geosmap.to_param, :situation_geosmap => valid_attributes}, valid_session
        response.should redirect_to(situation_geosmap)
      end
    end

    describe "with invalid params" do
      it "assigns the situation_geosmap as @situation_geosmap" do
        situation_geosmap = SituationGeosmap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SituationGeosmap.any_instance.stub(:save).and_return(false)
        put :update, {:id => situation_geosmap.to_param, :situation_geosmap => {  }}, valid_session
        assigns(:situation_geosmap).should eq(situation_geosmap)
      end

      it "re-renders the 'edit' template" do
        situation_geosmap = SituationGeosmap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SituationGeosmap.any_instance.stub(:save).and_return(false)
        put :update, {:id => situation_geosmap.to_param, :situation_geosmap => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested situation_geosmap" do
      situation_geosmap = SituationGeosmap.create! valid_attributes
      expect {
        delete :destroy, {:id => situation_geosmap.to_param}, valid_session
      }.to change(SituationGeosmap, :count).by(-1)
    end

    it "redirects to the situation_geosmaps list" do
      situation_geosmap = SituationGeosmap.create! valid_attributes
      delete :destroy, {:id => situation_geosmap.to_param}, valid_session
      response.should redirect_to(situation_geosmaps_url)
    end
  end

end
